# Generated by Django 5.2.7 on 2025-10-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='deleted',
        ),
        migrations.AddField(
            model_name='note',
            name='uploaded_at',
            field=models.BigIntegerField(default=0),
        ),
    ]
