# Generated by Django 5.2.7 on 2025-10-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_note_deleted_note_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='client_id',
        ),
        migrations.AlterField(
            model_name='note',
            name='uploaded_at',
            field=models.BigIntegerField(),
        ),
    ]
