# Generated by Django 5.2.7 on 2025-10-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_note_client_id_alter_note_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='author_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
